---
title: "730_Final_Project"
author: "Amani Chehimi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse) 
library(ggplot2)    
library(brms)       
library(posterior)  
library(tidybayes)
```

```{r}
original_dat <- read.csv("730projectdata.csv") %>%
  rename(y = totalscore)
```

## Data Cleaning

```{r}
dat <- original_dat

dat$REGION[dat$REGION > 4] <- NA
dat$AGE[dat$AGE > 85] <- NA
dat$SEX[dat$SEX > 2] <- NA
dat$RACENEW[dat$RACENEW > 600] <- NA
dat$EDUC[dat$EDUC > 600 | dat$EDUC == 0] <- NA
dat$POORYN[dat$POORYN == 9] <- NA
dat$ALCDAYSYR[dat$ALCDAYSYR > 366] <- NA
dat$CIGDAYMO[dat$CIGDAYMO > 31] <- NA
```

### Relevant Columns and Convert to Factors
```{r}
dat <- dat %>%
  select(c(REGION, AGE, SEX, RACENEW, EDUC, POORYN, ALCDAYSYR, CIGDAYMO, y)) %>%
  mutate(
    REGION = as.factor(REGION),
    SEX = as.factor(SEX),
    RACENEW = as.factor(RACENEW),
    POORYN = as.factor(POORYN)
  )
```

### Missingness and Drop High-Missingness Variables
```{r}
colmissings <- function(columninput) {
  round(sum(is.na(columninput)) / nrow(dat), 2)
}

apply(dat, 2, colmissings)

dat <- dat %>% select(-c(ALCDAYSYR, CIGDAYMO))
```


# Frequency-Based Dataset for Efficiency

## Age and Education Categories
```{r}
dat <- dat %>%
  mutate(
    AgeCat = case_when(
      AGE < 18 ~ "child",
      AGE >= 18 & AGE <= 30 ~ "youngAdult",
      AGE > 30 & AGE <= 60 ~ "Adult",
      AGE > 60 ~ "elderly"
    )
  )

dat <- dat %>%
  mutate(
    EduCat = case_when(
      EDUC <= 116 ~ "Grade 12 or less, no diploma",
      EDUC > 116 & EDUC <= 202 ~ "High school Diploma, GED, graduate",
      EDUC %in% c(300, 301, 302, 303, 400) ~ "Some college, AA or Bachelor's Degree",
      EDUC %in% c(500, 501, 502, 503, 504, 505) ~ "Graduate, Professional, or other Degree"
    )
  )
```

## Summarized Data into Frequency Form
```{r}
dat0 <- dat %>%
  filter(!is.na(AgeCat) & !is.na(SEX) & !is.na(RACENEW) & !is.na(EduCat) & !is.na(POORYN)) %>%
  group_by(y, REGION, AgeCat, SEX, RACENEW, EduCat, POORYN) %>%
  summarise(Freq = n(), .groups = "drop") %>%
  mutate(Weight = Freq / sum(Freq))  
```

```{r}
write.csv(dat0, "FreqCategories.csv", row.names = FALSE)
```


# Fitting the Baseline Model

```{r}
Freq_dat <- read_csv("FreqCategories.csv")
```

### Baseline Model Without Interaction Terms
```{r}
fit <- brm(
  y ~ (1 | REGION + AgeCat + SEX + RACENEW + EduCat + POORYN), 
  family = gaussian(), 
  data = dat0, 
  iter = 1000, 
  chains = 4, 
  cores = getOption("mc.cores", 4), 
  seed = 12345, 
  weights = Weight  
)
```

```{r}
summary(fit)
prior_summary(fit)
```


```{r}
pp_check(fit)
```

